# Opt-in rules
opt_in_rules:
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_direct_init
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - indentation_width
  - last_where
  - legacy_random
  - nslocalizedstring_key
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - return_arrow_whitespace
  - sorted_first_last
  - yoda_condition
  - unowned_variable_capture

analyzer_rules:
  - unused_import
  - unused_declaration
switch_case_alignment:
  indented_cases: true
force_try:
  severity: warning
overridden_super_call:
  severity: error
  included:
    # The '*' adds the built-in default set, e.g., UIKit
    - '*'
    - layoutSubviews()
    - commonInit()
  excluded:
    - setUpWithError()
    - tearDownWithError()
prohibited_super_call:
  severity: error
  included:
    # The '*' adds the built-in default set, e.g., UIKit
    - '*'

# Rule thresholds
file_length:
  warning: 500
  error: 700

function_parameter_count:
  warning: 5
  error: 8

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 400

type_name:
  min_length: 3
  max_length: 40

# Exclude paths
excluded:
  - Pods
  - Carthage
  - fastlane
  - build
  - DerivedData
  - .build
  - .swiftpm
  - .vscode
  - .idea
  - .jazzy
  - .mint
  - .xcframeworks
  - .xcodeproj
  - .playground
  - .git
